name: Android Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04 # Явно указываем версию ОС
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace --info
      
      - uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
